apiVersion: v1
kind: Template
metadata:
  name: skipper-osb-nexus
  annotations:
    openshift.io/display-name: Spring Cloud Skipper server with Nexus
    description: |-
      A retrofitted Spring Cloud Skipper server with Open Service Broker API support.
      Also includes a Nexus instance to support deploying Maven artifacts for use when
      deploying Maven deployer resources.
    iconClass: icon-spring
message: |-
  The Nexus instance credentials are admin:admin123.
labels:
   template: skipper-osb-nexus
objects:
  # oc adm policy add-scc-to-user anyuid system:serviceaccount:xxx:skipper
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      labels:
        template: skipper
      name: skipper

  # Nexus
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        template: skipper-osb-nexus
      name: nexus
    spec:
      triggers:
        - type: ConfigChange
      strategy:
        type: Recreate
      replicas: 1
      selector:
        name: nexus
      template:
        metadata:
          labels:
            name: nexus
        spec:
          containers:
            - name: nexus
              image: sonatype/nexus:2.14.5
              env:
                - name: CONTEXT_PATH
                  value: '/'
                - name: MIN_HEAP
                  value: ${MIN_HEAP}
                - name: MAX_HEAP
                  value: ${MAX_HEAP}
              ports:
                - name: http-8081
                  containerPort: 8081
                  protocol: TCP
              readinessProbe:
                httpGet:
                  path: /service/local/status
                  port: 8081
                initialDelaySeconds: 40
                timeoutSeconds: 5
                failureThreshold: 10
              livenessProbe:
                httpGet:
                  path: /service/local/status
                  port: 8081
                initialDelaySeconds: 40
                timeoutSeconds: 5
                failureThreshold: 10
              resources:
                limits:
                  cpu: ${SERVER_LIMITS_CPU}
                  memory: ${SERVER_LIMITS_MEMORY}
                requests:
                  cpu: ${SERVER_REQUESTS_CPU}
                  memory: ${SERVER_REQUESTS_MEMORY}
          restartPolicy: Always
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        template: skipper-osb-nexus
      name: nexus
    spec:
      ports:
        - name: http-80
          port: 80
          targetPort: http-8081
      selector:
        name: nexus

  # Skipper server
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: skipper-config
    data:
      application.yaml: |-
        health.config.enabled: false

        spring:
          cloud:
            skipper:
              server:
                enableLocalPlatform: false
                packageRepositories:
                  -
                    name: local
                    url: http://${spring.cloud.client.hostname}:7577
                    local: true
                    description: Default local database backed repository
                    repoOrder: 1
                platform:
                  openshift:
                    accounts:
                      skipper:
                        namespace: skipper
                        defaultDockerfile: Dockerfile.nexus
                        entryPointStyle: boot
                        requests:
                          cpu: 0
                        limits:
                          cpu: 4
        maven:
          remote-repositories.skipper: http://${NEXUS_ROUTE_HOST}/content/groups/public/
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        template: skipper-osb-nexus
      name: skipper
    spec:
      triggers:
        - type: ConfigChange
      strategy:
        type: Rolling
      replicas: 1
      selector:
        name: skipper
      template:
        metadata:
          labels:
            name: skipper
        spec:
          containers:
            - name: skipper
              image: springcloud/spring-cloud-skipper-server:1.0.0.BUILD-SNAPSHOT
              env:
                - name: SPRING_CONFIG_LOCATION
                  value: /var/skipper-config/application.yaml
              ports:
                - name: http-7577
                  containerPort: 7577
                  protocol: TCP
              readinessProbe:
                httpGet:
                  path: /actuator/info
                  port: 7577
                initialDelaySeconds: 20
                timeoutSeconds: 5
                failureThreshold: 10
              livenessProbe:
                httpGet:
                  path: /actuator/health
                  port: 7577
                initialDelaySeconds: 20
                timeoutSeconds: 5
                failureThreshold: 10
              resources:
                limits:
                  cpu: ${SERVER_LIMITS_CPU}
                  memory: ${SERVER_LIMITS_MEMORY}
                requests:
                  cpu: ${SERVER_REQUESTS_CPU}
                  memory: ${SERVER_REQUESTS_MEMORY}
              volumeMounts:
                - mountPath: /var/skipper-config
                  name: skipper-config
          volumes:
            - name: skipper-config
              configMap:
                name: skipper-config
          restartPolicy: Always
          serviceAccount: skipper
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        template: skipper-osb-nexus
      name: skipper
    spec:
      ports:
        - name: http-7577
          port: 7577
          targetPort: http-7577
      selector:
        name: skipper
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        template: skipper-osb-nexus
      name: skipper
    spec:
      to:
        kind: Service
        name: skipper
      port:
        targetPort: http-7577
parameters:
  - name: NEXUS_ROUTE_HOST
    displayName: The Nexus Route host
    description: The host where Nexus is accessible
    required: true
  - name: SERVER_REQUESTS_MEMORY
    displayName: Default memory request for the Data Flow Server
    description: "The default memory request for Nexus. See https://docs.openshift.org/latest/dev_guide/compute_resources.html#dev-compute-resources"
    value: "384Mi"
  - name: SERVER_REQUESTS_CPU
    displayName: Default CPU request for the Data Flow Server
    description: "The default CPU request for Nexus. See https://docs.openshift.org/latest/dev_guide/compute_resources.html#dev-compute-resources"
    value: "500m"
  - name: SERVER_LIMITS_MEMORY
    displayName: Default memory limit for the Data Flow Server
    description: "The default memory limit for Nexus. See https://docs.openshift.org/latest/dev_guide/compute_resources.html#dev-compute-resources"
    value: "512Mi"
  - name: SERVER_LIMITS_CPU
    displayName: Default CPU limit for the Data Flow Server
    description: "The default CPU limit for Nexus See https://docs.openshift.org/latest/dev_guide/compute_resources.html#dev-compute-resources"
    value: "4000m"
  - name: MIN_HEAP
    displayName: "Passed as -Xms. Defaults to 64m"
    description: "The default CPU limit for Nexus"
    value: "256m"
  - name: MAX_HEAP
    displayName: "Passed as -Xmx. Defaults to 128m"
    description: "The default CPU limit for Nexus"
    value: "384m"
